# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-kafka-adapter
  labels:
    kafka.eventing.knative.dev/release: devel
rules:
- apiGroups:
  - sources.knative.dev
  resources:
  - kafkasources
  verbs:
  - get
  - list
  - watch
  - patch

- apiGroups:
  - sources.knative.dev
  resources:
  - kafkasources/status
  verbs:
  - get

- apiGroups:
  - sources.knative.dev
  resources:
  - kafkasources/finalizers
  verbs:
  - get
  - patch
  - delete

- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch

- apiGroups:
   - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
