apiVersion: v1
data:
  sarama: |
    Admin:
      Timeout: 10000000000
    Net:
      TLS:
        Config:
          ClientAuth: 0
      SASL:
        Mechanism: PLAIN
        Version: 1
      KeepAlive: 30000000000
    Metadata:
      RefreshFrequency: 300000000000
    Consumer:
      Offsets:
        AutoCommit:
          Interval: 5000000000
        Retention: 604800000000000
    Producer:
      Idempotent: false  # This must be false if using Azure eventhubs, otherwise true is preferred
      RequiredAcks: -1
  eventing-kafka: |
    channel:
      cpuLimit: 200m
      cpuRequest: 100m
      memoryLimit: 100Mi
      memoryRequest: 50Mi
      replicas: 1
    default:
      numPartitions: 4
      replicationFactor: 1
      retentionMillis: 604800000
    dispatcher:
      cpuLimit: 500m
      cpuRequest: 300m
      memoryLimit: 128Mi
      memoryRequest: 50Mi
      replicas: 1
      retryInitialIntervalMillis: 500
      retryTimeMillis: 300000
      retryExponentialBackoff: true
    kafka:
      offset:
        commitAsync: false
        commitDurationMillis: 30000
        commitMessageCount: 50
      provider: azure
    metrics:
      domain: eventing-kafka
      port: 8081
    serviceAccount: eventing-kafka-channel-controller
kind: ConfigMap
metadata:
  name: config-eventing-kafka
  namespace: knative-eventing
