apiVersion: v1
data:
  sarama: |
    Net:
      TLS:
        Config:
          ClientAuth: 0
      SASL:
        Mechanism: PLAIN
        Version: "1"
    Metadata:
      RefreshFrequency: 300000000000
    Consumer:
      Offsets:
        AutoCommit:
          Interval: 5000000000
        Retention: 604800000000000
      Return:
        Errors: "true"
  eventing-kafka: |
    channel:
      cpuLimit: 200m
      cpuRequest: 100m
      memoryLimit: 100Mi
      memoryRequest: 50Mi
      replicas: 1
    default:
      numPartitions: 4
      replicationFactor: 1
      retentionMillis: 604800000
    dispatcher:
      cpuLimit: 500m
      cpuRequest: 300m
      memoryLimit: 128Mi
      memoryRequest: 50Mi
      replicas: 1
      retryInitialIntervalMillis: 500
      retryTimeMillis: 300000
      retryExponentialBackoff: true
    kafka:
      brokers: "eventhub.servicebus.windows.net:9093"
      offset:
        commitAsync: false
        commitDurationMillis: 30000
        commitMessageCount: 50
      password: TODO
      provider: azure
      secret: kafka-credentials
      username: $Connection-String
    metrics:
      domain: eventing-kafka
      port: 8081
    serviceAccount: eventing-kafka-channel-controller
kind: ConfigMap
metadata:
  name: config-eventing-kafka
  namespace: knative-eventing
