apiVersion: v1
kind: Service
metadata:
  name: eventing-kafka-channel-controller
  namespace: {{ .Values.global.namespace.eventing }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    k8s-app: eventing-kafka-channel-controller
spec:
  selector:
    app: eventing-kafka-channel-controller
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.kafka.networking.service.metricsPort }}
    targetPort: {{ .Values.kafka.networking.container.metricsPort }}
